# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    temporada_actual:
        class: AppBundle\Service\TemporadaActual
        arguments: ["@doctrine.orm.entity_manager"]
        #arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    calculo_liquidacion:
        class: AppBundle\Service\CalculoLiquidacion
        arguments: ["@doctrine.orm.entity_manager"]
    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_suscriber }
